### ISSUE TITLE
1.27.1+ support

### ISSUE THREAD

**Issue by Makonede** [etra0/botw-freecam#34]
I have the latest experimental version of Cemu, 2.0-13, and would like to be able to use this tool without downgrading (which breaks Cemu settings). Could you update this tool to be compatible with 1.27.1+? (Mark it as a prerelease so that people using 1.26.2f won't download an incompatible version by mistake.)

**Comment by SDarkMagic** [comment]
I also cannot get it to work with Cemu version 1.27.1, and it appears to have something to do with XInput blocker. I looked through past issues and it seems like this was a problem before #33 and simply required a different version of XInput blocker to be used with some adjustments made to how it was called and handled.

**Comment by TollyH** [comment]
I've temporarily mitigated this ~~[in my fork](https://github.com/TollyH/botw-freecam/releases/tag/v0.2.6-hack)~~ by completely disabling the XInput code. It allows the app to run and work, but without XInput it does mean you have to control the camera with the keyboard instead of a controller (asides from the rotation, which is controlled however you normally would).

**Comment by etra0** [comment]
According to Cemu's site, latest recommended version is still 1.26.2f, so as long as that doesn't change, I don't think I'll update it, because it would probably duplicate the effort if something changes with XInput.

I'd like to make it as generic as possible but due to personal time constraint, I can't.

**Comment by etra0** [comment]
So, I created a pre-release that will warn you if xinput is not detected and continue working (without controller support obviously).

Please test this as I do not have the latest version of Cemu (and don't plan to update it until it is the stable release).

https://github.com/etra0/botw-freecam/releases/tag/v0.2.7-rc1

**Comment by TollyH** [comment]
Seems to work fine, thanks!
